import 'package:flutter/material.dart';
import '../../core/services/patient_features_service.dart';
import '../../core/theme/app_colors.dart';
import '../../widgets/patient_page.dart';

class AddMemoryScreen extends StatefulWidget{const AddMemoryScreen({super.key});@override State<AddMemoryScreen> createState()=>_AddMemoryScreenState();}
class _AddMemoryScreenState extends State<AddMemoryScreen>{final title=TextEditingController(),date=TextEditingController(),location=TextEditingController(),people=TextEditingController(),description=TextEditingController();String emoji='📷',visibility='family';bool saving=false;@override void dispose(){for(final c in[title,date,location,people,description])c.dispose();super.dispose();}
Future<void> save()async{if(title.text.trim().isEmpty)return;setState(()=>saving=true);try{await PatientFeaturesService.addMemory({'title':title.text.trim(),'memory_date':date.text.trim(),'location':location.text.trim(),'people':people.text.trim(),'description':description.text.trim(),'emoji':emoji,'visibility':visibility});if(mounted)Navigator.pop(context,true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>saving=false);}}
@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:PatientPage(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_forward_ios_rounded)),const Expanded(child:Text('إضافة ذكرى',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900)))]),const SizedBox(height:18),const Text('اختاري رمزًا للذكرى',style:TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:8),Wrap(spacing:8,children:['📷','❤️','🌷','🎂','🌊','👨‍👩‍👧'].map((x)=>ChoiceChip(selected:emoji==x,label:Text(x,style:const TextStyle(fontSize:22)),onSelected:(_)=>setState(()=>emoji=x))).toList()),const SizedBox(height:16),_field(title,'عنوان الذكرى'),const SizedBox(height:10),_field(date,'التاريخ: YYYY-MM-DD',Icons.calendar_today_outlined),const SizedBox(height:10),_field(location,'المكان',Icons.location_on_outlined),const SizedBox(height:10),_field(people,'الأشخاص الموجودون',Icons.people_outline),const SizedBox(height:10),_field(description,'وصف قصير',null,4),const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:visibility,decoration:const InputDecoration(labelText:'الخصوصية',filled:true,fillColor:Colors.white),items:const[DropdownMenuItem(value:'family',child:Text('المريض والعائلة')),DropdownMenuItem(value:'patient',child:Text('المريض فقط'))],onChanged:(v)=>setState(()=>visibility=v??visibility)),const SizedBox(height:22),SizedBox(width:double.infinity,height:56,child:FilledButton(onPressed:title.text.trim().isEmpty||saving?null:save,style:FilledButton.styleFrom(backgroundColor:AppColors.primary),child:saving?const CircularProgressIndicator(color:Colors.white):const Text('حفظ الذكرى',style:TextStyle(fontWeight:FontWeight.w900))))]))));
Widget _field(TextEditingController c,String label,[IconData? icon,int lines=1])=>TextField(controller:c,maxLines:lines,onChanged:(_)=>setState((){}),decoration:InputDecoration(labelText:label,prefixIcon:icon==null?null:Icon(icon),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(17))));}
