import 'package:flutter/material.dart';
import '../../core/services/patient_features_service.dart';
import '../../core/theme/app_colors.dart';
import '../../widgets/patient_page.dart';

class DailyCheckInScreen extends StatefulWidget{const DailyCheckInScreen({super.key});@override State<DailyCheckInScreen> createState()=>_State();}
class _State extends State<DailyCheckInScreen>{String? mood,sleep,ready;double energy=3;bool needHelp=false,loading=true,saving=false;
@override void initState(){super.initState();_load();}
bool _bool(dynamic v)=>v==true||v==1||v?.toString()=='1';
Future<void> _load()async{try{final d=await PatientFeaturesService.loadCheckin();if(!mounted)return;setState((){mood=d==null?null:d['mood']?.toString();sleep=d==null?null:d['sleep_quality']?.toString();ready=d==null?null:d['readiness']?.toString();energy=double.tryParse(d==null?'':d['energy']?.toString()??'')??3;needHelp=_bool(d==null?null:d['need_help']);loading=false;});}catch(e){if(mounted)setState(()=>loading=false);}}
Future<void> _save()async{setState(()=>saving=true);try{await PatientFeaturesService.saveCheckin({'mood':mood,'sleep_quality':sleep,'readiness':ready,'energy':energy.round(),'need_help':needHelp});if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حفظ حالتك لليوم 🌷')));Navigator.pop(context,true);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>saving=false);}}
@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:PatientPage(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(loading)const LinearProgressIndicator(minHeight:2),Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_forward_ios_rounded)),const Expanded(child:Text('كيف حالك اليوم؟',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900)))]),const Text('تساعدنا إجاباتك على تخصيص تجربتك، ولا تُستخدم للتشخيص الطبي.',style:TextStyle(height:1.6,color:AppColors.textSecondary)),const SizedBox(height:22),const PatientSectionTitle(title:'كيف تشعر اليوم؟'),const SizedBox(height:10),Wrap(spacing:9,runSpacing:9,children:[('😊','جيد'),('🙂','مستقر'),('😐','عادي'),('😴','متعب')].map((x)=>ChoiceChip(selected:mood==x.$2,label:Text('${x.$1} ${x.$2}'),onSelected:(_)=>setState(()=>mood=x.$2))).toList()),const SizedBox(height:22),const PatientSectionTitle(title:'كيف كان نومك؟'),const SizedBox(height:9),Wrap(spacing:8,children:['جيد','متوسط','غير مريح'].map((x)=>ChoiceChip(selected:sleep==x,label:Text(x),onSelected:(_)=>setState(()=>sleep=x))).toList()),const SizedBox(height:22),const PatientSectionTitle(title:'هل أنت مستعد للتمرين؟'),const SizedBox(height:9),Row(children:[Expanded(child:ChoiceChip(selected:ready=='نعم',label:const SizedBox(width:double.infinity,child:Text('نعم',textAlign:TextAlign.center)),onSelected:(_)=>setState(()=>ready='نعم'))),const SizedBox(width:9),Expanded(child:ChoiceChip(selected:ready=='لاحقًا',label:const SizedBox(width:double.infinity,child:Text('أفضل لاحقًا',textAlign:TextAlign.center)),onSelected:(_)=>setState(()=>ready='لاحقًا')))]),const SizedBox(height:18),NeuroCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('مستوى الطاقة',style:TextStyle(fontWeight:FontWeight.w900)),Slider(value:energy,min:1,max:5,divisions:4,label:'${energy.round()} / 5',onChanged:(v)=>setState(()=>energy=v)),Center(child:Text('${energy.round()} من 5'))])),const SizedBox(height:10),NeuroCard(child:SwitchListTile(contentPadding:EdgeInsets.zero,value:needHelp,title:const Text('أحتاج مساعدة اليوم',style:TextStyle(fontWeight:FontWeight.w800)),onChanged:(v)=>setState(()=>needHelp=v))),const SizedBox(height:22),SizedBox(width:double.infinity,height:56,child:FilledButton(onPressed:mood==null||saving?null:_save,style:FilledButton.styleFrom(backgroundColor:AppColors.primary),child:saving?const CircularProgressIndicator(color:Colors.white):const Text('حفظ والمتابعة',style:TextStyle(fontWeight:FontWeight.w900))))]))));}
