import 'package:flutter/material.dart';
import '../../core/services/patient_features_service.dart';
import '../../core/theme/app_colors.dart';
import '../../widgets/patient_page.dart';
import 'memory_album_screen.dart';

class MemoryTreeScreen extends StatefulWidget{const MemoryTreeScreen({super.key});@override State<MemoryTreeScreen> createState()=>_MemoryTreeScreenState();}
class _MemoryTreeScreenState extends State<MemoryTreeScreen>{List<Map<String,dynamic>> memories=[];bool loading=true;@override void initState(){super.initState();_load();}Future<void> _load()async{try{final m=await PatientFeaturesService.loadMemories();if(mounted)setState((){memories=m;loading=false;});}catch(_){if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext context){final leafCount=memories.length>6?6:memories.length;return Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:PatientPage(child:Column(children:[if(loading)const LinearProgressIndicator(minHeight:2),Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_forward_ios_rounded)),const Expanded(child:Text('شجرة الذاكرة',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900)))]),const SizedBox(height:8),const Text('شجرتك تنمو مع كل ذكرى جميلة 🌿',style:TextStyle(color:AppColors.textSecondary)),const SizedBox(height:24),Container(width:300,height:330,decoration:BoxDecoration(color:const Color(0xFFFAF6EF),borderRadius:BorderRadius.circular(28),border:Border.all(color:AppColors.border)),child:Stack(alignment:Alignment.center,children:[const Positioned(bottom:35,child:Icon(Icons.park_rounded,size:220,color:Color(0xFF89A986))),...List.generate(leafCount,(i){const spots=[Offset(75,55),Offset(190,85),Offset(90,140),Offset(185,170),Offset(120,215),Offset(210,225)];return Positioned(left:spots[i].dx,top:spots[i].dy,child:CircleAvatar(backgroundColor:Colors.white,child:Text(memories[i]['emoji']?.toString()??'📷')));})])),const SizedBox(height:18),NeuroCard(color:const Color(0xFFEAF4ED),child:Row(children:[const Icon(Icons.eco_rounded,color:Color(0xFF71947A)),const SizedBox(width:10),Expanded(child:Text(memories.isEmpty?'ابدأ بإضافة أول ذكرى إلى شجرتك.':'تحتوي شجرتك على ${memories.length} ذكريات جميلة.'))])),const SizedBox(height:20),SizedBox(width:double.infinity,height:56,child:FilledButton.icon(onPressed:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const MemoryAlbumScreen()));if(mounted)_load();},style:FilledButton.styleFrom(backgroundColor:AppColors.primary),icon:const Icon(Icons.photo_library_outlined),label:const Text('فتح ألبوم الذكريات',style:TextStyle(fontWeight:FontWeight.w900))))]))));}}
