import 'package:flutter/material.dart';
import '../../core/services/patient_features_service.dart';
import '../../core/theme/app_colors.dart';
import '../../widgets/patient_page.dart';
import 'add_memory_screen.dart';
import 'memory_details_screen.dart';

class MemoryAlbumScreen extends StatefulWidget{const MemoryAlbumScreen({super.key});@override State<MemoryAlbumScreen> createState()=>_MemoryAlbumScreenState();}
class _MemoryAlbumScreenState extends State<MemoryAlbumScreen>{List<Map<String,dynamic>> items=[];bool loading=true;String? error;@override void initState(){super.initState();load();}Future<void> load()async{try{final x=await PatientFeaturesService.loadMemories();if(mounted)setState((){items=x;loading=false;error=null;});}catch(e){if(mounted)setState((){loading=false;error=e.toString().replaceFirst('Exception: ','');});}}
Future<void> add()async{final changed=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>const AddMemoryScreen()));if(changed==true)load();}
@override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:PatientPage(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[if(loading)const LinearProgressIndicator(minHeight:2),Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_forward_ios_rounded)),const Expanded(child:Text('ألبوم الذكريات',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900))),IconButton(onPressed:add,icon:const Icon(Icons.add_circle_outline_rounded))]),const Text('ذكرياتك المحفوظة في مكان واحد ❤️',style:TextStyle(color:AppColors.textSecondary)),const SizedBox(height:20),if(error!=null)NeuroCard(child:Column(children:[Text(error!),TextButton(onPressed:load,child:const Text('إعادة المحاولة'))]))else if(!loading&&items.isEmpty)NeuroCard(child:Column(children:[const Icon(Icons.photo_album_outlined,size:48),const SizedBox(height:10),const Text('لا توجد ذكريات بعد.'),TextButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('إضافة أول ذكرى'))]))else GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:items.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,mainAxisSpacing:11,crossAxisSpacing:11,mainAxisExtent:220),itemBuilder:(_,i){final m=items[i];return InkWell(borderRadius:BorderRadius.circular(21),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>MemoryDetailsScreen(title:m['title']?.toString()??'',date:m['memory_date']?.toString()??'',emoji:m['emoji']?.toString()??'📷',description:m['description']?.toString()??''))),child:Container(decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(21),border:Border.all(color:AppColors.border)),child:Column(children:[Expanded(child:Container(width:double.infinity,alignment:Alignment.center,decoration:const BoxDecoration(color:Color(0xFFF5ECE0),borderRadius:BorderRadius.vertical(top:Radius.circular(20))),child:Text(m['emoji']?.toString()??'📷',style:const TextStyle(fontSize:54)))),Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(m['title']?.toString()??'',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(m['memory_date']?.toString()??'',style:const TextStyle(fontSize:10,color:AppColors.textSecondary))]))])));}),const SizedBox(height:18),SizedBox(width:double.infinity,height:54,child:OutlinedButton.icon(onPressed:add,icon:const Icon(Icons.add_rounded),label:const Text('إضافة ذكرى جديدة')))]))));}
