name: neurobridge_mobile
description: NeuroBridge mobile application for patients and caregivers.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/neurobridge_logo.png

  fonts:
    - family: ArabicElegant
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
        - asset: assets/fonts/ArefRuqaa-Bold.ttf
          weight: 700

    - family: EnglishScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700
