import { useEffect, useMemo, useState } from "react";
import { api } from "../api/client";
import { useAuth } from "../auth/AuthContext";
import { ChatThread } from "../components/ChatThread";
import { Card, ErrorState, Spinner } from "../components/ui";
import { formatDateTime, initials } from "../lib";
import { useI18n } from "../i18n/useI18n";
import type { Lang } from "../i18n/translations";
import type { ProviderMessage, ProviderMessageListResponse, ProviderMessageReply, ProviderMessageThread } from "../types";

type View = "active" | "archived" | "deleted";
type ConfirmTarget = { kind: "clear" | "conversation" | "permanent"; id: string };
interface Preferences { archived: string[]; deleted: string[]; hidden: string[]; clearedAt: Record<string, string>; }
const emptyPreferences: Preferences = { archived: [], deleted: [], hidden: [], clearedAt: {} };
const preferenceKey = (userId?: string) => `nb_clinician_message_preferences:${userId || "current"}`;
const readPreferences = (userId?: string): Preferences => {
  try {
    const saved = JSON.parse(localStorage.getItem(preferenceKey(userId)) || "null") as Partial<Preferences> | null;
    return saved ? { archived: saved.archived || [], deleted: saved.deleted || [], hidden: saved.hidden || [], clearedAt: saved.clearedAt || {} } : emptyPreferences;
  } catch { return emptyPreferences; }
};

const copy: Record<Lang, Record<string, string>> = {
  en: { eyebrow: "Messages", title: "Messages", sub: "Stay connected with patients and families throughout their care journey.", search: "Search conversations...", conversations: "Conversations", empty: "No conversations here", emptyHelp: "Conversations in this section will appear here.", select: "Select a conversation", selectHelp: "Choose a message thread to view the conversation and reply.", family: "Family member", patient: "Patient", forPatient: "For {name}", viewOnly: "View only", replyUnavailable: "Restore this conversation to send a reply.", loadError: "Messages could not be loaded.", threadError: "This conversation could not be opened.", modalTitle: "Start a new conversation", modalSub: "Choose a patient or linked family member.", recipientSearch: "Search patients or family members...", noRecipients: "No additional eligible contacts are available. Existing contacts can be resumed here.", close: "Close", cleared: "This chat was cleared on this device.", clearedHelp: "New replies will continue to appear here." },
  ar: { eyebrow: "الرسائل", title: "الرسائل", sub: "ابقَ على تواصل مع المرضى والعائلات خلال كل مرحلة من رحلة الرعاية.", search: "ابحث في المحادثات...", conversations: "المحادثات", empty: "لا توجد محادثات هنا", emptyHelp: "ستظهر محادثات هذا القسم هنا.", select: "اختر محادثة", selectHelp: "اختر إحدى المحادثات لعرض الرسائل والرد عليها.", family: "فرد من العائلة", patient: "المريض", forPatient: "بخصوص {name}", viewOnly: "للعرض فقط", replyUnavailable: "استعد هذه المحادثة لإرسال رد.", loadError: "تعذّر تحميل الرسائل.", threadError: "تعذّر فتح هذه المحادثة.", modalTitle: "بدء محادثة جديدة", modalSub: "اختر مريضًا أو أحد أفراد العائلة المرتبطين به.", recipientSearch: "ابحث عن مريض أو فرد من العائلة...", noRecipients: "لا تتوفر جهات اتصال مؤهلة إضافية. يمكنك استئناف المحادثات الحالية من هنا.", close: "إغلاق", cleared: "تم مسح هذه المحادثة على هذا الجهاز.", clearedHelp: "ستستمر الردود الجديدة بالظهور هنا." },
  fr: { eyebrow: "Messages", title: "Messages", sub: "Restez en contact avec les patients et leurs familles tout au long de leur parcours de soins.", search: "Rechercher des conversations...", conversations: "Conversations", empty: "Aucune conversation ici", emptyHelp: "Les conversations de cette section apparaîtront ici.", select: "Sélectionnez une conversation", selectHelp: "Choisissez un fil pour consulter la conversation et répondre.", family: "Membre de la famille", patient: "Patient", forPatient: "Pour {name}", viewOnly: "Lecture seule", replyUnavailable: "Restaurez cette conversation pour répondre.", loadError: "Impossible de charger les messages.", threadError: "Impossible d’ouvrir cette conversation.", modalTitle: "Démarrer une nouvelle conversation", modalSub: "Choisissez un patient ou un membre de sa famille associé.", recipientSearch: "Rechercher un patient ou un proche...", noRecipients: "Aucun autre contact admissible n’est disponible. Vous pouvez reprendre les conversations existantes ici.", close: "Fermer", cleared: "Cette conversation a été effacée sur cet appareil.", clearedHelp: "Les nouvelles réponses continueront d’apparaître ici." },
  es: { eyebrow: "Mensajes", title: "Mensajes", sub: "Manténgase en contacto con los pacientes y sus familias durante todo su recorrido asistencial.", search: "Buscar conversaciones...", conversations: "Conversaciones", empty: "No hay conversaciones aquí", emptyHelp: "Las conversaciones de esta sección aparecerán aquí.", select: "Selecciona una conversación", selectHelp: "Elige un hilo para ver la conversación y responder.", family: "Familiar", patient: "Paciente", forPatient: "Para {name}", viewOnly: "Solo lectura", replyUnavailable: "Restaura esta conversación para responder.", loadError: "No se pudieron cargar los mensajes.", threadError: "No se pudo abrir esta conversación.", modalTitle: "Iniciar una nueva conversación", modalSub: "Elige un paciente o familiar vinculado.", recipientSearch: "Buscar pacientes o familiares...", noRecipients: "No hay contactos elegibles adicionales. Puedes reanudar aquí las conversaciones existentes.", close: "Cerrar", cleared: "Este chat se borró en este dispositivo.", clearedHelp: "Las nuevas respuestas seguirán apareciendo aquí." },
  de: { eyebrow: "Nachrichten", title: "Nachrichten", sub: "Bleiben Sie während des gesamten Versorgungswegs mit Patienten und Familien in Verbindung.", search: "Unterhaltungen durchsuchen...", conversations: "Unterhaltungen", empty: "Hier sind keine Unterhaltungen", emptyHelp: "Unterhaltungen in diesem Bereich werden hier angezeigt.", select: "Unterhaltung auswählen", selectHelp: "Wählen Sie einen Verlauf aus, um ihn anzusehen und zu antworten.", family: "Familienmitglied", patient: "Patient", forPatient: "Für {name}", viewOnly: "Nur lesen", replyUnavailable: "Stellen Sie diese Unterhaltung wieder her, um zu antworten.", loadError: "Nachrichten konnten nicht geladen werden.", threadError: "Diese Unterhaltung konnte nicht geöffnet werden.", modalTitle: "Neue Unterhaltung beginnen", modalSub: "Wählen Sie einen Patienten oder ein verknüpftes Familienmitglied.", recipientSearch: "Patienten oder Angehörige suchen...", noRecipients: "Keine weiteren berechtigten Kontakte verfügbar. Bestehende Unterhaltungen können hier fortgesetzt werden.", close: "Schließen", cleared: "Dieser Chat wurde auf diesem Gerät geleert.", clearedHelp: "Neue Antworten werden weiterhin hier angezeigt." },
};
const relations: Record<Lang, Record<string, string>> = {
  en: { son: "Son", daughter: "Daughter", wife: "Wife", husband: "Husband", spouse: "Spouse", caregiver: "Caregiver", family_member: "Family member" }, ar: { son: "الابن", daughter: "الابنة", wife: "الزوجة", husband: "الزوج", spouse: "الزوج/الزوجة", caregiver: "مقدم رعاية", family_member: "فرد من العائلة" }, fr: { son: "Fils", daughter: "Fille", wife: "Épouse", husband: "Époux", spouse: "Conjoint", caregiver: "Aidant", family_member: "Membre de la famille" }, es: { son: "Hijo", daughter: "Hija", wife: "Esposa", husband: "Esposo", spouse: "Cónyuge", caregiver: "Cuidador", family_member: "Familiar" }, de: { son: "Sohn", daughter: "Tochter", wife: "Ehefrau", husband: "Ehemann", spouse: "Partner/in", caregiver: "Betreuungsperson", family_member: "Familienmitglied" },
};
const fill = (value: string, name: string) => value.replace("{name}", name);

export function ClinicianMessagesPage() {
  const { user } = useAuth(); const { lang, t } = useI18n(); const c = copy[lang];
  const initial = useMemo(() => readPreferences(user?.id), [user?.id]);
  const [items, setItems] = useState<ProviderMessage[]>([]), [thread, setThread] = useState<ProviderMessageThread | null>(null);
  const [loading, setLoading] = useState(true), [threadLoading, setThreadLoading] = useState(false), [error, setError] = useState(""), [threadError, setThreadError] = useState("");
  const [query, setQuery] = useState(""), [mobileOpen, setMobileOpen] = useState(false), [view, setView] = useState<View>("active");
  const [archived, setArchived] = useState(new Set(initial.archived)), [deleted, setDeleted] = useState(new Set(initial.deleted)), [hidden, setHidden] = useState(new Set(initial.hidden));
  const [clearedAt, setClearedAt] = useState<Record<string, string>>(initial.clearedAt), [menuId, setMenuId] = useState<string | null>(null);
  const [newOpen, setNewOpen] = useState(false), [recipientQuery, setRecipientQuery] = useState(""), [confirmTarget, setConfirmTarget] = useState<ConfirmTarget | null>(null);

  const load = async () => { setLoading(true); setError(""); try { setItems((await api<ProviderMessageListResponse>("/provider-messages?limit=200")).messages); } catch { setError(c.loadError); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { try { localStorage.setItem(preferenceKey(user?.id), JSON.stringify({ archived: [...archived], deleted: [...deleted], hidden: [...hidden], clearedAt } satisfies Preferences)); } catch { /* session-local fallback */ } }, [archived, deleted, hidden, clearedAt, user?.id]);
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") { setNewOpen(false); setConfirmTarget(null); setMenuId(null); } };
    const onPointer = (event: MouseEvent) => { const target = event.target as Element; if (!target.closest(".conversation-menu,.conversation-menu-button,.chat-conversation-actions")) setMenuId(null); };
    window.addEventListener("keydown", onKey); document.addEventListener("mousedown", onPointer); return () => { window.removeEventListener("keydown", onKey); document.removeEventListener("mousedown", onPointer); };
  }, []);
  const relationship = (value?: string | null) => value ? (relations[lang][value] || value) : "";
  const inView = (item: ProviderMessage) => !hidden.has(item.id) && (view === "deleted" ? deleted.has(item.id) : !deleted.has(item.id) && (view === "archived" ? archived.has(item.id) : !archived.has(item.id)));
  const visible = useMemo(() => { const needle = query.trim().toLocaleLowerCase(); return [...items].filter((item) => inView(item) && (!needle || `${item.sender_name || ""} ${item.patient_name || ""}`.toLocaleLowerCase().includes(needle))).sort((a, b) => (b.latest_reply_at || b.created_at).localeCompare(a.latest_reply_at || a.created_at)); }, [items, query, view, archived, deleted, hidden]);
  const count = (target: View) => items.filter((item) => !hidden.has(item.id) && (target === "deleted" ? deleted.has(item.id) : !deleted.has(item.id) && (target === "archived" ? archived.has(item.id) : !archived.has(item.id)))).length;
  const recipients = useMemo(() => { const needle = recipientQuery.trim().toLocaleLowerCase(); const unique = new Map<string, ProviderMessage>(); items.filter((item) => !hidden.has(item.id)).forEach((item) => { if (!unique.has(item.sender_user_id)) unique.set(item.sender_user_id, item); }); return [...unique.values()].filter((item) => !needle || `${item.sender_name || ""} ${item.patient_name || ""} ${relationship(item.sender_relationship)}`.toLocaleLowerCase().includes(needle)); }, [items, hidden, recipientQuery, lang]);
  const open = async (item: ProviderMessage) => { setThreadLoading(true); setThreadError(""); setMobileOpen(true); setMenuId(null); try { const result = await api<ProviderMessageThread>(`/provider-messages/${item.id}`); setThread(result); await api(`/provider-messages/${item.id}/read`, { method: "PATCH" }).catch(() => undefined); setItems((current) => current.map((value) => value.id === item.id ? { ...value, unread_reply_count: 0 } : value)); } catch { setThread(null); setThreadError(c.threadError); } finally { setThreadLoading(false); } };
  const reply = async (body: string) => { if (!thread) return; const result = await api<ProviderMessageReply>(`/provider-messages/${thread.id}/replies`, { method: "POST", body: JSON.stringify({ body }) }); setThread((current) => current ? { ...current, status: "answered", replies: [...current.replies, result] } : current); setItems((current) => current.map((item) => item.id === thread.id ? { ...item, status: "answered", latest_reply_preview: result.body, latest_reply_at: result.created_at } : item)); };
  const archive = (id: string) => { setArchived((current) => new Set(current).add(id)); setDeleted((current) => { const next = new Set(current); next.delete(id); return next; }); setThread(null); setMobileOpen(false); setMenuId(null); };
  const restore = (id: string) => { setArchived((current) => { const next = new Set(current); next.delete(id); return next; }); setDeleted((current) => { const next = new Set(current); next.delete(id); return next; }); setView("active"); setMenuId(null); };
  const confirm = () => { if (!confirmTarget) return; const { id, kind } = confirmTarget; if (kind === "clear") setClearedAt((current) => ({ ...current, [id]: new Date().toISOString() })); else if (kind === "conversation") { setDeleted((current) => new Set(current).add(id)); setArchived((current) => { const next = new Set(current); next.delete(id); return next; }); setView("deleted"); setThread(null); setMobileOpen(false); } else { setHidden((current) => new Set(current).add(id)); setDeleted((current) => { const next = new Set(current); next.delete(id); return next; }); setThread(null); setMobileOpen(false); } setMenuId(null); setConfirmTarget(null); };
  const actions = (id: string, header = false) => <div className={`conversation-menu ${header ? "conversation-menu--header" : ""}`}>{deleted.has(id) ? <><button type="button" onClick={() => restore(id)}>↩ {t("family.restoreDeletedConversation")}</button><button type="button" className="is-danger" onClick={() => setConfirmTarget({ kind: "permanent", id })}>⌫ {t("family.deleteFromDevice")}</button></> : <>{archived.has(id) ? <button type="button" onClick={() => restore(id)}>↩ {t("family.restoreToActive")}</button> : <button type="button" onClick={() => archive(id)}>▣ {t("family.archiveConversation")}</button>}<button type="button" onClick={() => setConfirmTarget({ kind: "clear", id })}>◌ {t("family.clearChat")}</button><button type="button" className="is-danger" onClick={() => setConfirmTarget({ kind: "conversation", id })}>⌫ {t("family.deleteConversation")}</button></>}</div>;
  const activeItem = thread ? items.find((item) => item.id === thread.id) : undefined;
  const cutoff = thread ? clearedAt[thread.id] : undefined;
  const visibleReplies = thread ? thread.replies.filter((replyItem) => !cutoff || replyItem.created_at > cutoff) : [];

  return <div className="page page--wide family-messages-page clinician-messages"><div className="page__head"><div><span className="eyebrow">{c.eyebrow}</span><h1>{c.title}</h1><p className="page__sub">{c.sub}</p></div></div>{loading ? <div className="messages-state"><Spinner label={c.conversations} /></div> : error ? <div className="messages-state"><ErrorState message={error} onRetry={load} /></div> : <Card className={`messages-workspace clinician-messages__workspace ${mobileOpen ? "messages-workspace--open" : ""}`}>
    <aside className="msg-list clinician-messages__inbox"><div className="msg-list__head"><strong>{c.conversations}</strong><div className="conversation-head-actions"><small>{count(view)}</small><button type="button" className="new-conversation-button" onClick={() => setNewOpen(true)} aria-label={t("family.newConversationAction")} aria-expanded={newOpen}>＋</button></div></div><div className="conversation-tabs" role="tablist" aria-label={t("family.conversationFilter")}>{(["active", "archived", "deleted"] as View[]).map((tab) => <button key={tab} type="button" role="tab" aria-selected={view === tab} className={view === tab ? "is-active" : ""} onClick={() => { setView(tab); setThread(null); setMobileOpen(false); }}>{t(`family.${tab === "active" ? "activeConversations" : tab === "archived" ? "archivedConversations" : "deletedConversations"}`)} <small>{count(tab)}</small></button>)}</div><label className="msg-search"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={c.search} /></label><div className="msg-list__scroll">{visible.map((item) => { const unread = view === "deleted" ? 0 : item.unread_reply_count || 0; return <div className="conv-shell" key={item.id}><button type="button" className={`conv ${thread?.id === item.id ? "conv--active" : ""} ${unread ? "conv--unread" : ""}`} onClick={() => void open(item)}><span className="provider-avatar">{initials(item.sender_name || c.family)}</span><span className="conv__body"><span className="conv__row"><strong className="conv__name">{item.sender_name || c.family}</strong><time className="conv__time">{formatDateTime(item.latest_reply_at || item.created_at)}</time></span><span className="conv__role">{item.patient_name || c.patient}</span><span className="conv__row"><span className="conv__preview">{clearedAt[item.id] ? c.cleared : item.latest_reply_preview || item.message}</span>{unread > 0 && <span className="unread-dot">{unread}</span>}</span></span></button><button type="button" className="conversation-menu-button" onClick={() => setMenuId((current) => current === item.id ? null : item.id)} aria-label={t("family.conversationMenu", { name: item.sender_name || c.family })} aria-haspopup="menu" aria-expanded={menuId === item.id}>⋯</button>{menuId === item.id && actions(item.id)}</div>; })}{!visible.length && <div className="msg-list__empty"><span aria-hidden="true">✉</span><strong>{c.empty}</strong><p>{c.emptyHelp}</p></div>}</div></aside>
    <section className={`msg-panel clinician-messages__conversation ${thread ? "clinician-messages__thread" : ""}`}>{threadLoading ? <Spinner label={c.conversations} /> : threadError ? <ErrorState message={threadError} /> : thread ? <ChatThread variant="panel" originalId={thread.id} originalSenderId={thread.sender_user_id} originalSenderName={thread.sender_name} originalText={thread.message} originalAt={thread.created_at} replies={visibleReplies} hideOriginal={Boolean(cutoff)} emptyState={cutoff && !visibleReplies.length ? <div className="chat-empty demo-chat__empty"><span aria-hidden="true">✦</span><h3>{c.cleared}</h3><p>{c.clearedHelp}</p></div> : undefined} currentUserId={user?.id} canReply={!archived.has(thread.id) && !deleted.has(thread.id) && thread.provider_user_id === user?.id} disabledNote={c.replyUnavailable} onSend={reply} title={thread.sender_name || c.family} subtitle={`${thread.sender_relationship ? `${relationship(thread.sender_relationship)} · ` : ""}${fill(c.forPatient, thread.patient_name || c.patient)}`} statusLabel={thread.provider_user_id === user?.id ? undefined : c.viewOnly} avatarText={initials(thread.sender_name || c.family)} onBack={() => setMobileOpen(false)} headerActions={activeItem && <div className="chat-conversation-actions"><button type="button" onClick={() => setMenuId((current) => current === thread.id ? null : thread.id)} aria-label={t("family.conversationMenu", { name: thread.sender_name || c.family })} aria-haspopup="menu" aria-expanded={menuId === thread.id}>⋯</button>{menuId === thread.id && actions(thread.id, true)}</div>} /> : <div className="chat-empty msg-panel__empty"><span aria-hidden="true">✉</span><h3>{c.select}</h3><p>{c.selectHelp}</p></div>}</section>
  </Card>}
  {newOpen && <div className="new-conversation-dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setNewOpen(false); }}><div className="new-conversation-dialog" role="dialog" aria-modal="true" aria-labelledby="clinician-new-conversation-title"><header><div><h2 id="clinician-new-conversation-title">{c.modalTitle}</h2><p>{c.modalSub}</p></div><button type="button" onClick={() => setNewOpen(false)} aria-label={c.close}>×</button></header><label><span aria-hidden="true">⌕</span><input autoFocus value={recipientQuery} onChange={(event) => setRecipientQuery(event.target.value)} placeholder={c.recipientSearch} /></label><div className="new-conversation-dialog__results">{recipients.map((item) => <button type="button" key={item.sender_user_id} onClick={() => { setNewOpen(false); setRecipientQuery(""); void open(item); }}><span className="provider-avatar">{initials(item.sender_name || c.family)}</span><span><strong>{item.sender_name || c.family}</strong><small>{item.patient_name || c.patient}{item.sender_relationship ? ` · ${relationship(item.sender_relationship)}` : ""}</small></span></button>)}{!recipients.length && <div className="new-conversation-dialog__empty">{c.noRecipients}</div>}</div></div></div>}
  {confirmTarget && <div className="confirm-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setConfirmTarget(null); }}><div className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="clinician-confirm-title"><span aria-hidden="true">{confirmTarget.kind === "clear" ? "◌" : "⌫"}</span><h2 id="clinician-confirm-title">{confirmTarget.kind === "clear" ? t("family.clearChatTitle") : confirmTarget.kind === "permanent" ? t("family.permanentDeleteTitle") : t("family.moveToDeletedTitle")}</h2><p>{confirmTarget.kind === "clear" ? t("family.clearChatDescription") : confirmTarget.kind === "permanent" ? t("family.permanentDeleteDescription") : t("family.moveToDeletedDescription")}</p><div><button type="button" className="btn btn--ghost" onClick={() => setConfirmTarget(null)}>{t("common.cancel")}</button><button type="button" className="btn confirm-delete" onClick={confirm}>{confirmTarget.kind === "clear" ? t("family.clearChat") : confirmTarget.kind === "permanent" ? t("family.deletePermanently") : t("family.moveToDeleted")}</button></div></div></div>}
  </div>;
}
