import { useEffect, useMemo, useState } from "react";
import { resolveMediaUrl as resolveProjectMediaUrl } from "../api/client";
import { webAccountApi } from "../api/webAccountClient";
import { useAuth } from "../auth/AuthContext";
import { useI18n } from "../i18n/useI18n";
import { initials } from "../lib";
import { familyBookingCopy } from "../lib/familyBookingCopy";
import { demoSlots, type DemoFamilyAppointment, type DemoPaymentMethod } from "../lib/familyBookingDemo";
import type { PatientProfile, Provider } from "../types";
import { FamilyMemberAvatar, useFamilyMembers } from "../familyMembers";
import { useCurrentFamilyPatient } from "../currentFamilyPatient";

const steps = ["patient", "provider", "dateTime", "appointmentType", "review", "payment", "confirmation"] as const;
const money = (n:number,l:string) => new Intl.NumberFormat(l,{style:"currency",currency:"USD"}).format(n);
const dateText = (d:string,l:string) => new Intl.DateTimeFormat(l,{dateStyle:"medium"}).format(new Date(`${d}T12:00:00`));
const resolveMediaUrl = (value:string) => resolveProjectMediaUrl(value) || undefined;
const appointmentTypeCopy={en:"Remote",ar:"موعد عن بُعد",fr:"À distance",es:"A distancia",de:"Online"} as const;
const remoteLocationCopy={en:"Remote appointment",ar:"موعد عن بُعد",fr:"Rendez-vous à distance",es:"Cita a distancia",de:"Online-Termin"} as const;

export function FamilyAppointmentsPage() {
  const {lang}=useI18n(); const c={...familyBookingCopy[lang],remote:appointmentTypeCopy[lang]}; const {user}=useAuth();
  const {active,members}=useFamilyMembers();
  const {patients,patient:currentPatient,copy:patientCopy,name:linkedPatientName}=useCurrentFamilyPatient();
  const [patient,setPatient]=useState<PatientProfile|null>(null),[providers,setProviders]=useState<Provider[]>([]),[loading,setLoading]=useState(true);
  const [items,setItems]=useState<DemoFamilyAppointment[]>([]),[tab,setTab]=useState<"upcoming"|"past"|"cancelled">("upcoming");
  const [open,setOpen]=useState(false),[step,setStep]=useState(0),[providerId,setProviderId]=useState(""),[search,setSearch]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState(""),[type,setType]=useState<"in_person"|"remote">("in_person");
  const [method,setMethod]=useState<DemoPaymentMethod>("card"),[payerType,setPayerType]=useState<"patient"|"family">("family"),[payerName,setPayerName]=useState(user?.full_name||""),[relationship,setRelationship]=useState("");
  const [cardholder,setCardholder]=useState(""),[cardNumber,setCardNumber]=useState(""),[expiry,setExpiry]=useState(""),[cvv,setCvv]=useState(""),[paymentError,setPaymentError]=useState(false);
  const [receipt,setReceipt]=useState<DemoFamilyAppointment|null>(null),[details,setDetails]=useState<DemoFamilyAppointment|null>(null),[cancelTarget,setCancelTarget]=useState<DemoFamilyAppointment|null>(null),[rescheduleTarget,setRescheduleTarget]=useState<DemoFamilyAppointment|null>(null);
  const [payingId,setPayingId]=useState<string|null>(null);
  const [pageError,setPageError]=useState<string|null>(null),[saving,setSaving]=useState(false);
  useEffect(()=>{setPatient(currentPatient)},[currentPatient?.id]);
  const loadAppointments=async()=>{setLoading(true);setPageError(null);try{const result=await webAccountApi<{success:boolean;providers:Provider[];appointments:DemoFamilyAppointment[]}>("family_appointments.php");setProviders(result.providers);setItems(result.appointments)}catch(reason){setPageError(reason instanceof Error?reason.message:"تعذر تحميل المواعيد")}finally{setLoading(false)}};
  useEffect(()=>{void loadAppointments()},[]);
  useEffect(()=>{if(!receipt||receipt.bookedByName)return;const payer=members.find(member=>member.name===receipt.payerName)||active;const attributed={...receipt,bookedByMemberId:active?.id,bookedByName:active?.name||"Omar",bookedByRelationship:active?.relationship||"son",payerMemberId:receipt.payerType==="family"?payer?.id:undefined,payerRelationship:receipt.payerType==="family"?(payer?.relationship||"son"):undefined};setReceipt(attributed);setItems(current=>current.map(item=>item.id===receipt.id?attributed:item))},[receipt,active,members]);
  useEffect(()=>{if(step!==5)return;document.querySelector<HTMLInputElement>(".payment-fields input")?.setAttribute("list","family-member-options")},[step,payerType]);
  useEffect(()=>{const member=members.find(value=>value.name===payerName);if(member)setRelationship(member.relationship)},[payerName,members]);
  const selectedProvider=providers.find(p=>p.provider_user_id===providerId)||null;
  const providerResults=useMemo(()=>{const q=search.trim().toLowerCase();return providers.filter(p=>!q||`${p.full_name} ${p.specialty||""}`.toLowerCase().includes(q))},[providers,search]);
  const visible=useMemo(()=>items.filter(i=>i.patientId===currentPatient?.id).map(i=>i.type==="remote"?{...i,location:remoteLocationCopy[lang]}:i).filter(i=>tab==="cancelled"?i.appointmentStatus==="cancelled":tab==="past"?i.appointmentStatus==="completed"||new Date(i.date)<new Date(new Date().toDateString()):!(["cancelled","completed"] as string[]).includes(i.appointmentStatus)&&new Date(i.date)>=new Date(new Date().toDateString())).sort((a,b)=>a.date.localeCompare(b.date)),[items,tab,currentPatient?.id,lang]);
  const reset=()=>{setStep(0);setProviderId("");setSearch("");setDate("");setTime("");setType("in_person");setMethod("card");setPayerType("family");setPayerName(active?.name||"");setRelationship(active?.relationship||"");setCardholder("");setCardNumber("");setExpiry("");setCvv("");setPaymentError(false);setPayingId(null)};
  const close=()=>{setOpen(false);reset()};
  const canContinue=step===0?!!patient:step===1?!!selectedProvider:step===2?!!date&&!!time:step===5?(method!=="card"||!!cardholder&&!!cardNumber&&!!expiry&&!!cvv)&&!!(payerType==="patient"||payerName):true;
  const finish=async()=>{
    if(!patient||!selectedProvider)return;
    setSaving(true);setPageError(null);
    try{
      const payload=payingId
        ? {id:payingId,action:"pay",payment_method:method,payer_type:payerType,payer_name:payerType==="patient"?patient.user?.full_name||c.patient:payerName,payer_relationship:payerType==="family"?relationship:""}
        : {patient_id:patient.id,provider_id:selectedProvider.provider_user_id,date,time,type,location:type==="remote"?c.remote:selectedProvider.clinic_name||selectedProvider.location||c.inPerson,reason:"حجز موعد من حساب العائلة",payment_method:method,payer_type:payerType,payer_name:payerType==="patient"?patient.user?.full_name||c.patient:payerName,payer_relationship:payerType==="family"?relationship:"",booked_by_name:active?.name||user?.full_name||"العائلة",booked_by_relationship:active?.relationship||""};
      const result=await webAccountApi<{success:boolean;appointment:DemoFamilyAppointment}>("family_appointments.php",{method:payingId?"PATCH":"POST",body:JSON.stringify(payload)});
      setItems(x=>[result.appointment,...x.filter(i=>i.id!==result.appointment.id)]);
      setReceipt(result.appointment);setCardholder("");setCardNumber("");setExpiry("");setCvv("");setStep(6);
    }catch(reason){setPaymentError(true);setPageError(reason instanceof Error?reason.message:"تعذر حفظ الموعد")}
    finally{setSaving(false)}
  };
  const payExisting=(i:DemoFamilyAppointment)=>{reset();setPayingId(i.id);setProviderId(i.providerId);setDate(i.date);setTime(i.time);setType(i.type);setPayerName(i.payerName);setOpen(true);setStep(5)};
  const confirmCancel=async()=>{if(!cancelTarget)return;setSaving(true);try{const result=await webAccountApi<{success:boolean;appointment:DemoFamilyAppointment}>("family_appointments.php",{method:"PATCH",body:JSON.stringify({id:cancelTarget.id,action:"cancel"})});setItems(x=>x.map(i=>i.id===result.appointment.id?result.appointment:i));setCancelTarget(null)}catch(reason){setPageError(reason instanceof Error?reason.message:"تعذر إلغاء الموعد")}finally{setSaving(false)}};
  const confirmReschedule=async()=>{if(!rescheduleTarget||!date||!time)return;setSaving(true);try{const result=await webAccountApi<{success:boolean;appointment:DemoFamilyAppointment}>("family_appointments.php",{method:"PATCH",body:JSON.stringify({id:rescheduleTarget.id,action:"reschedule",date,time})});setItems(x=>x.map(i=>i.id===result.appointment.id?result.appointment:i));setRescheduleTarget(null);setDate("");setTime("")}catch(reason){setPageError(reason instanceof Error?reason.message:"تعذر تغيير الموعد")}finally{setSaving(false)}};
  return <div className="page page--wide family-appt-page">
    <div className="page__head family-appt-intro"><div><span className="eyebrow">{c.eyebrow}</span><h1>{c.title}</h1><p className="page__sub">{c.description}</p>{currentPatient&&<small className="patient-context-line">{patientCopy.current}: {linkedPatientName(currentPatient)}</small>}</div><button className="btn btn--gold" onClick={()=>{reset();setPatient(currentPatient);setOpen(true)}}>+ {c.book}</button></div>
    {pageError&&<div className="banner banner--warn">{pageError} <button type="button" onClick={()=>void loadAppointments()}>إعادة المحاولة</button></div>}
    <datalist id="family-member-options">{members.map(member=><option value={member.name} key={member.id}>{member.name}</option>)}</datalist>
    <div className="family-appt-tabs">{(["upcoming","past","cancelled"] as const).map(k=><button key={k} className={tab===k?"is-active":""} onClick={()=>setTab(k)}>{c[k]}</button>)}</div>
    {loading?<div className="family-appt-empty">…</div>:visible.length===0?<div className="family-appt-empty"><span>◷</span><p>{c.noAppointments}</p><button onClick={()=>setOpen(true)}>{c.book}</button></div>:<div className="family-appt-grid">{visible.map(i=><article className="family-appt-card" key={i.id}><header><span className="provider-avatar">{initials(i.providerName)}</span><div><h2>{i.providerName}</h2><p>{i.providerRole==="therapist"?c.therapist:c.doctor}{i.providerSpecialty?` · ${i.providerSpecialty}`:""}</p></div><button className="family-appt-menu" aria-label={c.menu}>•••</button></header><div className="family-appt-card__facts"><div><span>{c.dateTime}</span><strong>{dateText(i.date,lang)} · <bdi>{i.time}</bdi></strong></div><div><span>{c.appointmentType}</span><strong className={`appointment-mode-badge appointment-mode-badge--${i.type==="remote"?"online":"in-person"}`}>{i.type==="remote"?c.onlineAppointment:c.inPersonAppointment}</strong>{i.type==="remote"&&<small className="appointment-video-note">{c.videoLinkNotice}</small>}</div>{i.type==="in_person"&&<div className="family-appt-card__location"><span>{c.location}</span><strong>{i.location}</strong></div>}</div><div className="family-appt-status"><span className={`status-pill status-pill--${i.appointmentStatus}`}>{c[i.appointmentStatus]}</span><span className={`status-pill status-pill--${i.paymentStatus}`}>{c[i.paymentStatus]}</span></div><footer><button onClick={()=>setDetails(i)}>{c.viewDetails}</button>{i.paymentStatus==="pending"&&<button className="is-primary" onClick={()=>payExisting(i)}>{c.payNow}</button>}{i.appointmentStatus!=="cancelled"&&<><button onClick={()=>{setRescheduleTarget(i);setDate(i.date);setTime(i.time)}}>{c.reschedule}</button><button className="is-danger" onClick={()=>setCancelTarget(i)}>{c.cancel}</button></>}</footer></article>)}</div>}
    {open&&<div className="booking-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="booking-dialog" role="dialog" aria-modal="true"><header><div><span>{c.book}</span><h2>{c[steps[step]]}</h2></div><button onClick={close}>×</button></header><div className="booking-progress">{steps.map((name,n)=><span key={name} className={n<=step?"is-active":""}><i>{n+1}</i><small>{c[name]}</small></span>)}</div><div className="booking-body">
      {step===0&&<div><h3>{c.patient}</h3>{patients.length?patients.map(item=><button key={item.id} className={`choice-card ${patient?.id===item.id?"is-selected":""}`} onClick={()=>setPatient(item)}><span className="provider-avatar">{initials(item.user?.full_name)}</span><span><strong>{linkedPatientName(item)}</strong><small>{patientCopy.patient}</small></span><b>{patient?.id===item.id?"✓":""}</b></button>):<p>{patientCopy.none}</p>}</div>}
      {step===1&&<div><label className="booking-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={c.searchProvider}/></label><div className="provider-choice-grid">{providerResults.map(p=><button key={p.provider_user_id} className={`choice-card ${providerId===p.provider_user_id?"is-selected":""}`} onClick={()=>setProviderId(p.provider_user_id)}>{p.photo_url?<img className="provider-avatar" src={resolveMediaUrl(p.photo_url)} alt=""/>:<span className="provider-avatar">{initials(p.full_name)}</span>}<span><strong>{p.full_name}</strong><small>{p.role==="therapist"?c.therapist:c.doctor}{p.specialty?` · ${p.specialty}`:""}</small></span><b>{providerId===p.provider_user_id?"✓":""}</b></button>)}</div></div>}
      {step===2&&<DateTime c={c} lang={lang} date={date} time={time} setDate={setDate} setTime={setTime}/>}
      {step===3&&<div className="type-options">{(["in_person","remote"] as const).map(v=><button className={`choice-card ${type===v?"is-selected":""}`} onClick={()=>setType(v)} key={v}><span className="booking-type-icon">{v==="remote"?"◉":"⌂"}</span><span><strong>{v==="remote"?c.remote:c.inPerson}</strong><small>{selectedProvider?.clinic_name||selectedProvider?.location||"NeuroBridge"}</small></span><b>{type===v?"✓":""}</b></button>)}</div>}
      {step===4&&<Summary c={c} lang={lang} patientName={patient?.user?.full_name||c.demoPatient} providerName={selectedProvider?.full_name||"—"} date={date} time={time} type={type}/>}
      {step===5&&<div className="payment-step"><h3>{c.whoPays}</h3><div className="segmented">{(["patient","family"] as const).map(v=><button className={payerType===v?"is-active":""} onClick={()=>setPayerType(v)} key={v}>{v==="patient"?c.patientPays:c.familyPays}</button>)}</div>{payerType==="family"&&<div className="payment-fields"><label>{c.payerName}<input value={payerName} onChange={e=>setPayerName(e.target.value)}/></label><label>{c.relationship}<input value={relationship} onChange={e=>setRelationship(e.target.value)}/></label></div>}<div className="payment-methods">{(["card","apple","google","center","later"] as DemoPaymentMethod[]).map(v=><button className={method===v?"is-selected":""} onClick={()=>setMethod(v)} key={v}>{c[v]}</button>)}</div>{method==="card"&&<PaymentCardFields c={c} cardholder={cardholder} setCardholder={setCardholder} cardNumber={cardNumber} setCardNumber={setCardNumber} expiry={expiry} setExpiry={setExpiry} cvv={cvv} setCvv={setCvv}/>}<p className="payment-demo-notice">ⓘ {c.demoNotice}</p>{["center","later"].includes(method)&&<p>{c.payAtCenterNote}</p>}{paymentError&&<div className="payment-error"><strong>{pageError||c.paymentFailed}</strong><button onClick={()=>setPaymentError(false)}>{c.tryAgain}</button></div>}<div className="payment-total"><span>{c.fee}</span><strong>{money(25,lang)}</strong><span>{c.total}</span><strong>{money(25,lang)}</strong></div></div>}
      {step===6&&receipt&&<div className="booking-success"><span>✓</span><h2>{receipt.paymentStatus==="paid"?c.paymentSuccessful:c.appointmentConfirmed}</h2><p>{c.appointmentConfirmed}</p><Summary c={c} lang={lang} patientName={receipt.patientName} providerName={receipt.providerName} date={receipt.date} time={receipt.time} type={receipt.type}/>{receipt.receiptReference&&<button onClick={()=>setDetails(receipt)}>{c.viewReceipt}</button>}</div>}
    </div><footer className="booking-footer">{step>0&&step<6&&<button onClick={()=>setStep(v=>v-1)}>{c.back}</button>}<span/>{step<5&&<button className="btn btn--gold" disabled={!canContinue} onClick={()=>setStep(v=>v+1)}>{step===4?c.continuePayment:c.next}</button>}{step===5&&<button className="btn btn--gold" disabled={!canContinue||saving} onClick={()=>void finish()}>{saving?"…":["center","later"].includes(method)?c.confirmBooking:c.completePayment}</button>}{step===6&&<button className="btn btn--gold" onClick={close}>{c.close}</button>}</footer></section></div>}
    {details&&<ReceiptModal item={details} c={c} lang={lang} onClose={()=>setDetails(null)}/>}
    {cancelTarget&&<ConfirmModal c={c} onCancel={()=>setCancelTarget(null)} onConfirm={confirmCancel}/>}
    {rescheduleTarget&&<div className="booking-backdrop"><section className="mini-dialog"><header><h2>{c.rescheduleTitle}</h2><button onClick={()=>setRescheduleTarget(null)}>×</button></header><DateTime c={c} lang={lang} date={date} time={time} setDate={setDate} setTime={setTime}/><footer><button onClick={()=>setRescheduleTarget(null)}>{c.back}</button><button className="btn btn--gold" disabled={!date||!time} onClick={confirmReschedule}>{c.confirmReschedule}</button></footer></section></div>}
  </div>;
}

type Copy=typeof familyBookingCopy.en;
function PaymentCardFields({c,cardholder,setCardholder,cardNumber,setCardNumber,expiry,setExpiry,cvv,setCvv}:{c:Copy;cardholder:string;setCardholder:(value:string)=>void;cardNumber:string;setCardNumber:(value:string)=>void;expiry:string;setExpiry:(value:string)=>void;cvv:string;setCvv:(value:string)=>void}){
  const visibleNumber=(cardNumber.replace(/\s/g,"")+"••••••••••••••••").slice(0,16).replace(/(.{4})/g,"$1 ").trim();
  return <div className="payment-card-section">
    <div className="payment-card-preview" dir="ltr">
      <div className="payment-card-preview__top"><span className="payment-card-preview__brand">NeuroBridge</span><span className="payment-card-preview__contactless">)))</span></div>
      <span className="payment-card-preview__chip" aria-hidden="true"/>
      <strong className="payment-card-preview__number"><bdi>{visibleNumber}</bdi></strong>
      <div className="payment-card-preview__bottom"><span><small>{c.cardholder}</small><bdi>{cardholder.trim()||"CARD HOLDER"}</bdi></span><span><small>{c.expiry}</small><bdi>{expiry||"MM/YY"}</bdi></span><span><small>CVV</small><bdi>{cvv.replace(/./g,"•")||"•••"}</bdi></span></div>
    </div>
    <div className="demo-card-form">
      <label>{c.cardholder}<input autoComplete="cc-name" value={cardholder} onChange={e=>setCardholder(e.target.value.slice(0,40))}/></label>
      <label className="full">{c.cardNumber}<input dir="ltr" inputMode="numeric" autoComplete="cc-number" placeholder="4242 4242 4242 4242" value={cardNumber} onChange={e=>{const digits=e.target.value.replace(/\D/g,"").slice(0,16);setCardNumber(digits.replace(/(.{4})/g,"$1 ").trim())}}/></label>
      <label>{c.expiry}<input dir="ltr" inputMode="numeric" autoComplete="cc-exp" placeholder="08/30" value={expiry} onChange={e=>{const digits=e.target.value.replace(/\D/g,"").slice(0,4);setExpiry(digits.length>2?`${digits.slice(0,2)}/${digits.slice(2)}`:digits)}}/></label>
      <label>{c.cvv}<input dir="ltr" inputMode="numeric" type="password" autoComplete="cc-csc" placeholder="123" value={cvv} onChange={e=>setCvv(e.target.value.replace(/\D/g,"").slice(0,4))}/></label>
    </div>
  </div>
}
function DateTime({c,lang,date,time,setDate,setTime}:{c:Copy;lang:string;date:string;time:string;setDate:(v:string)=>void;setTime:(v:string)=>void}){return <div className="date-time-step"><h3>{c.chooseDate}</h3><div className="date-options">{demoSlots().map(s=><button className={date===s.date?"is-selected":""} onClick={()=>{setDate(s.date);setTime("")}} key={s.date}>{dateText(s.date,lang)}</button>)}</div>{date&&<><h3>{c.chooseTime}</h3><div className="time-options">{demoSlots().find(s=>s.date===date)?.times.map(v=><button className={time===v?"is-selected":""} onClick={()=>setTime(v)} key={v}><bdi>{v}</bdi></button>)}</div></>}</div>}
function Summary({c,lang,patientName,providerName,date,time,type}:{c:Copy;lang:string;patientName:string;providerName:string;date:string;time:string;type:"in_person"|"remote"}){const {active,copy}=useFamilyMembers();return <dl className="booking-summary-final"><div><dt>{c.patient}</dt><dd>{patientName}</dd></div><div><dt>{c.provider}</dt><dd>{providerName}</dd></div><div><dt>{c.dateTime}</dt><dd>{dateText(date,lang)} · <bdi>{time}</bdi></dd></div><div><dt>{c.appointmentType}</dt><dd>{type==="remote"?c.remote:c.inPerson}</dd></div><div><dt>{copy.bookedBy}</dt><dd className="family-attribution"><FamilyMemberAvatar member={active}/><span><strong>{active?.name||"—"}</strong>{active&&<small>{copy.relationships[active.relationship]}</small>}</span></dd></div><div><dt>{c.amount}</dt><dd>{money(25,lang)}</dd></div></dl>}
function ConfirmModal({c,onCancel,onConfirm}:{c:Copy;onCancel:()=>void;onConfirm:()=>void}){return <div className="booking-backdrop"><section className="confirm-dialog"><h2>{c.cancelTitle}</h2><p>{c.cancelMessage}</p><footer><button onClick={onCancel}>{c.keep}</button><button className="btn btn--danger" onClick={onConfirm}>{c.confirmCancel}</button></footer></section></div>}
export function ReceiptModal({item,c,lang,onClose}:{item:DemoFamilyAppointment;c:Copy;lang:string;onClose:()=>void}){const {copy}=useFamilyMembers();const relationship=(value?:string)=>value&&value in copy.relationships?copy.relationships[value as keyof typeof copy.relationships]:value||"";const booked=`${item.bookedByName||"Omar"} · ${relationship(item.bookedByRelationship||"son")}`;const paid=item.payerType==="patient"?c.patient:`${item.payerName} · ${relationship(item.payerRelationship)}`;return <div className="booking-backdrop"><section className="receipt-dialog"><header><div><span>NB</span><h2>NeuroBridge</h2><small>{c.receipt}</small></div><button onClick={onClose}>×</button></header><p className="receipt-ref">{c.reference}: <bdi>{item.receiptReference||"—"}</bdi></p><dl>{[[c.patient,item.patientName],[copy.bookedBy,booked],[copy.paidBy,paid],[c.provider,item.providerName],[c.dateTime,`${dateText(item.date,lang)} · ${item.time}`],[c.method,item.maskedMethod||c[item.paymentMethod]],[c.amount,money(item.amount,lang)],[c.status,c[item.paymentStatus]]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><footer><button onClick={onClose}>{c.close}</button><button className="btn btn--gold" onClick={()=>window.print()}>{c.printReceipt}</button></footer></section></div>}
