import { createContext,useContext,useEffect,useMemo,useState,type FormEvent,type ReactNode } from "react";
import { webAccountApi } from "./api/webAccountClient";
import { useAuth } from "./auth/AuthContext";
import { useI18n } from "./i18n/useI18n";
import { patientName } from "./lib";
import { localizeFamilyRelationship } from "./familyMembers";
import type { PatientListResponse,PatientProfile } from "./types";

const STORAGE_KEY="nb_current_family_patient",AVATAR_KEY="nb_family_patient_avatars";
const text={
 en:{supporting:"Who are you supporting?",current:"Current patient",switchPatient:"Switch patient",link:"Link patient",all:"All patients",defaultPatient:"Default patient",defaultHelp:"Choose which patient is selected when you open the Family portal.",linked:"Linked patients",linkedHelp:"Manage patients linked to the Family account and add a photo to identify each patient more easily.",setCurrent:"Set as current patient",addPhoto:"Add photo",changePhoto:"Change photo",removePhoto:"Remove photo",save:"Save",cancel:"Cancel",none:"No patient is linked to this account",noneHelp:"Link a patient to start following appointments, memories, and activities.",patient:"Patient",forPatient:"For patient"},
 ar:{supporting:"من تتابع الآن؟",current:"المريض الحالي",switchPatient:"تبديل المريض",link:"ربط مريض",all:"كل المرضى",defaultPatient:"المريض الافتراضي",defaultHelp:"اختر المريض الذي يظهر تلقائيًا عند فتح بوابة العائلة.",linked:"المرضى المرتبطون",linkedHelp:"إدارة المرضى المرتبطين بحساب العائلة واختيار الصورة التي تساعدك على تمييز كل مريض.",setCurrent:"تعيين كمريض حالي",addPhoto:"إضافة صورة",changePhoto:"تغيير الصورة",removePhoto:"إزالة الصورة",save:"حفظ",cancel:"إلغاء",none:"لا يوجد مريض مرتبط بالحساب",noneHelp:"اربط مريضًا للبدء بمتابعة المواعيد والذكريات والأنشطة.",patient:"المريض",forPatient:"للمريض"},
 fr:{supporting:"Qui accompagnez-vous ?",current:"Patient actuel",switchPatient:"Changer de patient",link:"Lier un patient",all:"Tous les patients",defaultPatient:"Patient par défaut",defaultHelp:"Choisissez le patient sélectionné à l’ouverture du portail Famille.",linked:"Patients liés",linkedHelp:"Gérez les patients liés au compte Famille et ajoutez une photo pour mieux les identifier.",setCurrent:"Définir comme patient actuel",addPhoto:"Ajouter une photo",changePhoto:"Changer la photo",removePhoto:"Supprimer la photo",save:"Enregistrer",cancel:"Annuler",none:"Aucun patient n’est lié à ce compte",noneHelp:"Liez un patient pour suivre ses rendez-vous, souvenirs et activités.",patient:"Patient",forPatient:"Pour le patient"},
 es:{supporting:"¿A quién estás apoyando?",current:"Paciente actual",switchPatient:"Cambiar paciente",link:"Vincular paciente",all:"Todos los pacientes",defaultPatient:"Paciente predeterminado",defaultHelp:"Elige el paciente seleccionado al abrir el portal familiar.",linked:"Pacientes vinculados",linkedHelp:"Gestiona los pacientes vinculados a la cuenta familiar y añade una foto para identificarlos fácilmente.",setCurrent:"Establecer como paciente actual",addPhoto:"Añadir foto",changePhoto:"Cambiar foto",removePhoto:"Eliminar foto",save:"Guardar",cancel:"Cancelar",none:"No hay pacientes vinculados a esta cuenta",noneHelp:"Vincula un paciente para seguir citas, recuerdos y actividades.",patient:"Paciente",forPatient:"Para el paciente"},
 de:{supporting:"Wen unterstützen Sie?",current:"Aktueller Patient",switchPatient:"Patient wechseln",link:"Patient verknüpfen",all:"Alle Patienten",defaultPatient:"Standardpatient",defaultHelp:"Wählen Sie den Patienten, der beim Öffnen des Familienportals ausgewählt ist.",linked:"Verknüpfte Patienten",linkedHelp:"Verwalten Sie die mit dem Familienkonto verknüpften Patienten und fügen Sie zur leichteren Erkennung ein Foto hinzu.",setCurrent:"Als aktuellen Patienten festlegen",addPhoto:"Foto hinzufügen",changePhoto:"Foto ändern",removePhoto:"Foto entfernen",save:"Speichern",cancel:"Abbrechen",none:"Mit diesem Konto ist kein Patient verknüpft",noneHelp:"Verknüpfen Sie einen Patienten, um Termine, Erinnerungen und Aktivitäten zu verfolgen.",patient:"Patient",forPatient:"Für Patient"}
};
type Value={patients:PatientProfile[];patient:PatientProfile|null;loading:boolean;error:string|null;setPatient:(id:string)=>void;name:(value?:PatientProfile|null)=>string;relationship:(value?:PatientProfile|null)=>string;avatar:(id?:string|null)=>string|undefined;setAvatar:(id:string,value:string)=>void;removeAvatar:(id:string)=>void;copy:typeof text.en;reload:()=>Promise<void>};
const Context=createContext<Value|null>(null);
export function CurrentFamilyPatientProvider({children}:{children:ReactNode}){
 const {isFamily,user}=useAuth();const {lang}=useI18n();
 const [patients,setPatients]=useState<PatientProfile[]>([]);
 const [selectedId,setSelectedId]=useState<string|null>(()=>localStorage.getItem(STORAGE_KEY));
 const [avatars,setAvatars]=useState<Record<string,string>>(()=>{try{const saved=JSON.parse(localStorage.getItem(AVATAR_KEY)||"{}");return saved&&typeof saved==="object"?saved:{}}catch{return {}}});
 const [loading,setLoading]=useState(isFamily);const [error,setError]=useState<string|null>(null);
 const reload=async()=>{if(!isFamily){setPatients([]);setLoading(false);return}setLoading(true);setError(null);try{const result=await webAccountApi<PatientListResponse>("family_patients.php");setPatients(result.patients)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load linked patients");setPatients([])}finally{setLoading(false)}};
 useEffect(()=>{void reload()},[isFamily]);
 useEffect(()=>{if(loading)return;const valid=patients.some(item=>item.id===selectedId);const next=valid?selectedId:patients[0]?.id||null;if(next!==selectedId)setSelectedId(next);if(next)localStorage.setItem(STORAGE_KEY,next);else localStorage.removeItem(STORAGE_KEY)},[patients,selectedId,loading]);
 useEffect(()=>{try{localStorage.setItem(AVATAR_KEY,JSON.stringify(avatars))}catch{/* keep the preview usable for this session if storage is full */}},[avatars]);
 const patient=patients.find(item=>item.id===selectedId)||null;
 const familyUserId=user?.id?.replace(/^family:/,"")??"";
 const value=useMemo<Value>(()=>({patients,patient,loading,error,setPatient:id=>{if(patients.some(item=>item.id===id))setSelectedId(id)},name:value=>patientName(value?.user),relationship:value=>localizeFamilyRelationship(value?.family_links?.find(link=>link.family_user_id===familyUserId&&link.active)?.relationship,lang),avatar:id=>id?avatars[id]:undefined,setAvatar:(id,data)=>setAvatars(current=>({...current,[id]:data})),removeAvatar:id=>setAvatars(current=>{const next={...current};delete next[id];return next}),copy:text[lang],reload}),[patients,patient,loading,error,familyUserId,lang,avatars]);
 return <Context.Provider value={value}>{children}</Context.Provider>
}
export function useCurrentFamilyPatient(){const value=useContext(Context);if(!value)throw new Error("useCurrentFamilyPatient must be used inside CurrentFamilyPatientProvider");return value}
export function PatientAvatar({patient,className="",src}:{patient:PatientProfile|null;className?:string;src?:string}){const {avatar}=useCurrentFamilyPatient();const [failed,setFailed]=useState(false);const value=patientName(patient?.user)||"Patient",image=src||avatar(patient?.id);useEffect(()=>setFailed(false),[image]);return <span className={`patient-context-avatar ${className}`} aria-hidden="true">{image&&!failed?<img src={image} alt="" onError={()=>setFailed(true)}/>:value.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}</span>}

export function resizePatientAvatar(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("Invalid image"));image.onload=()=>{const size=256,scale=Math.min(size/image.width,size/image.height,1),width=Math.max(1,Math.round(image.width*scale)),height=Math.max(1,Math.round(image.height*scale)),canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const context=canvas.getContext("2d");if(!context){reject(new Error("Canvas unavailable"));return}context.clearRect(0,0,size,size);context.drawImage(image,(size-width)/2,(size-height)/2,width,height);resolve(canvas.toDataURL("image/webp",.82))};image.src=String(reader.result)};reader.readAsDataURL(file)})}

const linkDialogText={
 en:{body:"Enter the code shown in the patient's account.",code:"Patient code",hint:"Example: NB4CD95246",relationship:"Relationship",submit:"Link patient",success:"Patient linked successfully",relations:["Father","Mother","Son","Daughter","Spouse","Family member"]},
 ar:{body:"أدخلي كود المريض الموجود في حساب المريض، ثم اختاري صلة القرابة.",code:"كود المريض",hint:"مثال: NB4CD95246",relationship:"صلة القرابة",submit:"ربط المريض",success:"تم ربط المريض بنجاح",relations:["أب","أم","ابن","ابنة","زوج/زوجة","فرد من العائلة"]},
 fr:{body:"Saisissez le code affiché dans le compte du patient.",code:"Code patient",hint:"Exemple : NB4CD95246",relationship:"Lien de parenté",submit:"Lier le patient",success:"Patient lié avec succès",relations:["Père","Mère","Fils","Fille","Conjoint(e)","Membre de la famille"]},
 es:{body:"Introduce el código de la cuenta del paciente.",code:"Código del paciente",hint:"Ejemplo: NB4CD95246",relationship:"Relación",submit:"Vincular paciente",success:"Paciente vinculado correctamente",relations:["Padre","Madre","Hijo","Hija","Cónyuge","Familiar"]},
 de:{body:"Geben Sie den Code aus dem Patientenkonto ein.",code:"Patientencode",hint:"Beispiel: NB4CD95246",relationship:"Beziehung",submit:"Patient verknüpfen",success:"Patient erfolgreich verknüpft",relations:["Vater","Mutter","Sohn","Tochter","Ehepartner/in","Familienmitglied"]}
};
export function LinkPatientDialog({open,onClose}:{open:boolean;onClose:()=>void}){
 const {lang}=useI18n();const {copy,reload}=useCurrentFamilyPatient();const content=linkDialogText[lang];
 const [patientCode,setPatientCode]=useState("");const [relationship,setRelationship]=useState(content.relations[0]);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState<string|null>(null);
 useEffect(()=>{if(open){setPatientCode("");setRelationship(content.relations[0]);setError(null);setSuccess(null);setBusy(false)}},[open,lang]);
 if(!open)return null;
 const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError(null);setSuccess(null);try{await webAccountApi("family_patients.php",{method:"POST",body:JSON.stringify({patient_code:patientCode.trim().toUpperCase(),relationship})});await reload();setSuccess(content.success);setTimeout(onClose,700)}catch(reason){setError(reason instanceof Error?reason.message:"تعذر ربط المريض")}finally{setBusy(false)}};
 return <div className="link-patient-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="link-patient-dialog" role="dialog" aria-modal="true" aria-labelledby="link-patient-title"><button className="link-patient-close" onClick={onClose} aria-label={copy.cancel}>×</button><span aria-hidden="true">＋</span><h2 id="link-patient-title">{copy.link}</h2><p>{content.body}</p><form className="link-patient-form" onSubmit={submit}><label>{content.code}<input autoFocus required maxLength={20} value={patientCode} onChange={event=>setPatientCode(event.target.value.toUpperCase())} placeholder={content.hint} autoComplete="off"/></label><label>{content.relationship}<select value={relationship} onChange={event=>setRelationship(event.target.value)}>{content.relations.map(value=><option key={value} value={value}>{value}</option>)}</select></label>{error&&<div className="link-patient-message link-patient-message--error" role="alert">{error}</div>}{success&&<div className="link-patient-message link-patient-message--success" role="status">{success}</div>}<div className="link-patient-actions"><button type="button" className="btn btn--ghost" onClick={onClose} disabled={busy}>{copy.cancel}</button><button type="submit" className="btn btn--gold" disabled={busy||!patientCode.trim()}>{busy?"…":content.submit}</button></div></form></section></div>
}
