import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { useI18n } from "./i18n/useI18n";
import { useAuth } from "./auth/AuthContext";

export type FamilyRelationship = "son"|"daughter"|"husband"|"wife"|"brother"|"sister"|"grandson"|"granddaughter"|"father"|"mother"|"other";
export interface FamilyMember { id:string; name:string; relationship:FamilyRelationship; avatar?:string; }
const MEMBERS_KEY="nb_family_members",ACTIVE_KEY="nb_active_family_member",EVENT="nb-family-members";
const defaults:FamilyMember[]=[];
const copy={
 en:{current:"Current family member",who:"Who’s using the account?",add:"Add family member",edit:"Edit",remove:"Remove",members:"Family members",membersHelp:"Manage the family members who use this shared account.",name:"Name",relationship:"Relationship",selectHelp:"Select your name so this action is attributed correctly.",save:"Save",cancel:"Cancel",guidance:"More than one family member can use the same account. Select who is currently using it so memories, messages, bookings, and payments show the correct family member.",bookedBy:"Booked by",paidBy:"Paid by",me:"Me",another:"Another family member",sharedBy:"Shared by",from:"From",relationships:{son:"Son",daughter:"Daughter",husband:"Husband",wife:"Wife",brother:"Brother",sister:"Sister",grandson:"Grandson",granddaughter:"Granddaughter",father:"Father",mother:"Mother",other:"Other relative"}},
 ar:{current:"فرد العائلة الحالي",who:"من يستخدم الحساب الآن؟",add:"إضافة فرد",edit:"تعديل",remove:"إزالة",members:"أفراد العائلة",membersHelp:"حرّر الأشخاص الذين يستخدمون هذا الحساب العائلي المشترك.",name:"الاسم",relationship:"صلة القرابة",selectHelp:"اختر اسمك حتى يظهر مصدر الإجراء بشكل صحيح.",save:"حفظ",cancel:"إلغاء",guidance:"يمكن لأكثر من فرد من العائلة استخدام الحساب نفسه. اختر اسم الشخص الذي يستخدم الحساب حاليًا حتى تظهر الذكريات والرسائل والحجوزات والمدفوعات باسم صاحبها الصحيح.",bookedBy:"تم الحجز بواسطة",paidBy:"تم الدفع بواسطة",me:"أنا",another:"فرد آخر من العائلة",sharedBy:"شاركها",from:"من",relationships:{son:"ابن",daughter:"ابنة",husband:"زوج",wife:"زوجة",brother:"أخ",sister:"أخت",grandson:"حفيد",granddaughter:"حفيدة",father:"أب",mother:"أم",other:"قريب آخر"}},
 fr:{current:"Membre actuel",who:"Qui utilise le compte ?",add:"Ajouter un membre",edit:"Modifier",remove:"Supprimer",members:"Membres de la famille",membersHelp:"Gérez les membres qui utilisent ce compte familial partagé.",name:"Nom",relationship:"Lien de parenté",selectHelp:"Sélectionnez votre nom pour attribuer correctement cette action.",save:"Enregistrer",cancel:"Annuler",guidance:"Plusieurs membres de la famille peuvent utiliser le même compte. Sélectionnez la personne qui l’utilise afin d’attribuer correctement souvenirs, messages, réservations et paiements.",bookedBy:"Réservé par",paidBy:"Payé par",me:"Moi",another:"Un autre membre",sharedBy:"Partagé par",from:"De",relationships:{son:"Fils",daughter:"Fille",husband:"Mari",wife:"Épouse",brother:"Frère",sister:"Sœur",grandson:"Petit-fils",granddaughter:"Petite-fille",father:"Père",mother:"Mère",other:"Autre proche"}},
 es:{current:"Familiar actual",who:"¿Quién usa la cuenta?",add:"Añadir familiar",edit:"Editar",remove:"Eliminar",members:"Familiares",membersHelp:"Gestiona los familiares que usan esta cuenta compartida.",name:"Nombre",relationship:"Relación",selectHelp:"Selecciona tu nombre para atribuir correctamente esta acción.",save:"Guardar",cancel:"Cancelar",guidance:"Varios familiares pueden usar la misma cuenta. Selecciona quién la usa actualmente para atribuir correctamente recuerdos, mensajes, reservas y pagos.",bookedBy:"Reservado por",paidBy:"Pagado por",me:"Yo",another:"Otro familiar",sharedBy:"Compartido por",from:"De",relationships:{son:"Hijo",daughter:"Hija",husband:"Esposo",wife:"Esposa",brother:"Hermano",sister:"Hermana",grandson:"Nieto",granddaughter:"Nieta",father:"Padre",mother:"Madre",other:"Otro familiar"}},
 de:{current:"Aktuelles Familienmitglied",who:"Wer nutzt das Konto?",add:"Familienmitglied hinzufügen",edit:"Bearbeiten",remove:"Entfernen",members:"Familienmitglieder",membersHelp:"Verwalten Sie die Personen, die dieses gemeinsame Familienkonto nutzen.",name:"Name",relationship:"Beziehung",selectHelp:"Wählen Sie Ihren Namen, damit die Aktion richtig zugeordnet wird.",save:"Speichern",cancel:"Abbrechen",guidance:"Mehrere Familienmitglieder können dasselbe Konto nutzen. Wählen Sie die aktuelle Person, damit Erinnerungen, Nachrichten, Buchungen und Zahlungen korrekt zugeordnet werden.",bookedBy:"Gebucht von",paidBy:"Bezahlt von",me:"Ich",another:"Anderes Familienmitglied",sharedBy:"Geteilt von",from:"Von",relationships:{son:"Sohn",daughter:"Tochter",husband:"Ehemann",wife:"Ehefrau",brother:"Bruder",sister:"Schwester",grandson:"Enkel",granddaughter:"Enkelin",father:"Vater",mother:"Mutter",other:"Anderer Verwandter"}}
};
const extendedRelationships={
 en:{caregiver:"Caregiver",family_member:"Family member",family:"Family member"},
 ar:{caregiver:"مقدم رعاية",family_member:"فرد العائلة",family:"فرد العائلة"},
 fr:{caregiver:"Aidant",family_member:"Membre de la famille",family:"Membre de la famille"},
 es:{caregiver:"Cuidador",family_member:"Miembro de la familia",family:"Miembro de la familia"},
 de:{caregiver:"Betreuungsperson",family_member:"Familienmitglied",family:"Familienmitglied"}
} as const;
export function localizeFamilyRelationship(value:string|null|undefined,lang:keyof typeof copy){if(!value)return "";const normalized=value.trim().toLowerCase().replace(/[\s-]+/g,"_");if(normalized in copy.en.relationships)return copy[lang].relationships[normalized as FamilyRelationship];if(normalized in extendedRelationships.en)return extendedRelationships[lang][normalized as keyof typeof extendedRelationships.en];return value}
function readMembers(){try{const value=JSON.parse(localStorage.getItem(MEMBERS_KEY)||"null");return Array.isArray(value)?(value as FamilyMember[]).filter(member=>!member.id.startsWith("demo-")):defaults}catch{return defaults}}
type ContextValue={members:FamilyMember[];active:FamilyMember|null;copy:typeof copy.en;label:(member:FamilyMember|null)=>string;setActive:(id:string|null)=>void;add:(value:Omit<FamilyMember,"id">)=>void;update:(value:FamilyMember)=>void;remove:(id:string)=>void};
const Context=createContext<ContextValue|null>(null);
export function FamilyMemberProvider({children}:{children:ReactNode}){const {lang}=useI18n();const {user,isFamily}=useAuth();const [members,setMembers]=useState(readMembers);const [activeId,setActiveId]=useState<string|null>(()=>localStorage.getItem(ACTIVE_KEY)||null);useEffect(()=>{if(!isFamily||!user)return;const realId=user.id;setMembers(current=>{const withoutDemo=current.filter(member=>!member.id.startsWith("demo-"));const existing=withoutDemo.find(member=>member.id===realId);if(existing)return withoutDemo.map(member=>member.id===realId?{...member,name:user.full_name}:member);return [{id:realId,name:user.full_name,relationship:"other"},...withoutDemo]});setActiveId(realId)},[isFamily,user?.id,user?.full_name]);const active=members.find(m=>m.id===activeId)||null;useEffect(()=>{localStorage.setItem(MEMBERS_KEY,JSON.stringify(members));if(activeId)localStorage.setItem(ACTIVE_KEY,activeId);else localStorage.removeItem(ACTIVE_KEY);window.dispatchEvent(new Event(EVENT))},[members,activeId]);const value=useMemo<ContextValue>(()=>({members,active,copy:copy[lang],label:m=>m?`${m.name} · ${localizeFamilyRelationship(m.relationship,lang)}`:"",setActive:setActiveId,add:v=>{const member={...v,id:`member-${Date.now()}`};setMembers(x=>[...x,member]);setActiveId(member.id)},update:v=>setMembers(x=>x.map(m=>m.id===v.id?v:m)),remove:id=>{setMembers(x=>x.filter(m=>m.id!==id));if(activeId===id)setActiveId(null)}}),[members,active,activeId,lang]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useFamilyMembers(){const value=useContext(Context);if(!value)throw new Error("useFamilyMembers must be used inside FamilyMemberProvider");return value}
export const familyRelationshipOptions=Object.keys(copy.en.relationships) as FamilyRelationship[];

export const familyMemberPhotoCopy={
 en:{addPhoto:"Add photo",changePhoto:"Change photo",removePhoto:"Remove photo",removeMember:"Remove member",openAi:"Open AI Companion"},
 ar:{addPhoto:"إضافة صورة",changePhoto:"تغيير الصورة",removePhoto:"إزالة الصورة",removeMember:"حذف الفرد",openAi:"فتح المساعد الذكي"},
 fr:{addPhoto:"Ajouter une photo",changePhoto:"Changer la photo",removePhoto:"Supprimer la photo",removeMember:"Supprimer le membre",openAi:"Ouvrir le compagnon IA"},
 es:{addPhoto:"Añadir foto",changePhoto:"Cambiar foto",removePhoto:"Eliminar foto",removeMember:"Eliminar familiar",openAi:"Abrir el asistente de IA"},
 de:{addPhoto:"Foto hinzufügen",changePhoto:"Foto ändern",removePhoto:"Foto entfernen",removeMember:"Familienmitglied entfernen",openAi:"KI-Begleiter öffnen"}
};

export function FamilyMemberAvatar({member,className=""}:{member:FamilyMember|null;className?:string}){
 const [failed,setFailed]=useState(false);
 useEffect(()=>setFailed(false),[member?.avatar]);
 const fallback=(member?.name||"Family").trim().split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase();
 return <span className={`family-member-avatar ${className}`} aria-hidden="true">{member?.avatar&&!failed?<img src={member.avatar} alt="" onError={()=>setFailed(true)}/>:fallback}</span>;
}

export function resizeFamilyMemberAvatar(file:File):Promise<string>{
 return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("Invalid image"));image.onload=()=>{const size=256,scale=Math.min(size/image.width,size/image.height,1),width=Math.max(1,Math.round(image.width*scale)),height=Math.max(1,Math.round(image.height*scale));const canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const context=canvas.getContext("2d");if(!context){reject(new Error("Canvas unavailable"));return}context.clearRect(0,0,size,size);context.drawImage(image,(size-width)/2,(size-height)/2,width,height);resolve(canvas.toDataURL("image/webp",.82))};image.src=String(reader.result)};reader.readAsDataURL(file)});
}

export function FamilyIdentityRequired({open,onClose}:{open:boolean;onClose:()=>void}){const {members,setActive,copy}=useFamilyMembers();if(!open)return null;return <div className="family-member-backdrop"><section className="family-member-required" role="dialog" aria-modal="true"><h2>{copy.who}</h2><p>{copy.selectHelp}</p><div>{members.map(m=><button key={m.id} onClick={()=>{setActive(m.id);onClose()}}><strong>{m.name}</strong><small>{copy.relationships[m.relationship]}</small></button>)}</div><button className="member-modal-cancel" onClick={onClose}>{copy.cancel}</button></section></div>}
