import type { Lang } from "./i18n/translations";

export type ProviderRole = "doctor" | "therapist";
type RoleCopy = {
  greeting: string; dashboardSub: string; heroTitle: string; heroBody: string;
  patientsEyebrow: string; patientsTitle: string; patientsBody: string; patientsCta: string;
  appointmentsEyebrow: string; appointmentsTitle: string; appointmentsBody: string;
  aiLabel: string; aiDescription: string; aiHelp: string; aiPlaceholder: string;
  aiSuggestions: { id: string; title: string; helper: string }[];
};

const therapist: Record<Lang, RoleCopy> = {
  en:{greeting:"Welcome, {name}",dashboardSub:"Review therapy progress, prepare for upcoming sessions, and keep each patient’s plan moving forward.",heroTitle:"Every session is another step toward meaningful progress.",heroBody:"Follow activities, progress, appointments, and the patients who may benefit from thoughtful follow-up.",patientsEyebrow:"THERAPY PROGRESS",patientsTitle:"Progress grows through consistent support.",patientsBody:"Follow each patient’s activities, sessions, and progress throughout their therapy journey.",patientsCta:"View all patients",appointmentsEyebrow:"THERAPY SESSIONS",appointmentsTitle:"Every session creates space for meaningful progress.",appointmentsBody:"Prepare for upcoming therapy appointments and stay connected with each patient’s journey.",aiLabel:"Therapy assistant",aiDescription:"Support for organizing therapy information, preparing for sessions, and planning thoughtful follow-up.",aiHelp:"I can organize information you provide, prepare session questions, identify follow-up points, and draft supportive communication.",aiPlaceholder:"Ask for help organizing therapy information or preparing for a session...",aiSuggestions:[{id:"progress",title:"Help me organize the information I have about this patient’s progress.",helper:"Structure only the progress details I provide"},{id:"session",title:"Help me prepare questions for the next therapy session.",helper:"Organize useful questions and discussion points"},{id:"followup",title:"Help me identify useful follow-up points from the information I provide.",helper:"Review only the information shared here"},{id:"message",title:"Help me draft a supportive message to the patient or family.",helper:"Create clear wording for me to review"}]},
  ar:{greeting:"مرحبًا، {name}",dashboardSub:"راجع تقدّم العلاج، واستعد للجلسات القادمة، وتابع خطة كل مريض خطوة بخطوة.",heroTitle:"كل جلسة هي خطوة جديدة نحو تقدّم ملموس.",heroBody:"تابع الأنشطة والتقدّم والمواعيد، وركّز على المرضى الذين يحتاجون إلى متابعة مدروسة.",patientsEyebrow:"التقدّم العلاجي",patientsTitle:"التقدّم يبدأ بمتابعة مستمرة ودعم مناسب.",patientsBody:"تابع أنشطة المريض وجلساته وتقدّمه خلال رحلته العلاجية.",patientsCta:"عرض جميع المرضى",appointmentsEyebrow:"الجلسات العلاجية",appointmentsTitle:"كل جلسة تفتح مجالًا لتقدّم ملموس.",appointmentsBody:"استعد للجلسات العلاجية القادمة وابقَ قريبًا من رحلة كل مريض.",aiLabel:"مساعد المعالج",aiDescription:"مساعدة في تنظيم معلومات العلاج، والاستعداد للجلسات، وترتيب المتابعة مع المريض.",aiHelp:"يمكنني تنظيم المعلومات التي تقدمها، وتحضير أسئلة الجلسة، وتحديد نقاط المتابعة، وصياغة تواصل داعم.",aiPlaceholder:"اطلب المساعدة في تنظيم معلومات العلاج أو التحضير لجلسة...",aiSuggestions:[{id:"progress",title:"ساعدني في تنظيم المعلومات التي لدي عن تقدّم هذا المريض.",helper:"نظّم فقط تفاصيل التقدّم التي أقدّمها"},{id:"session",title:"ساعدني في تحضير أسئلة للجلسة العلاجية القادمة.",helper:"نظّم الأسئلة ونقاط النقاش المفيدة"},{id:"followup",title:"ساعدني في تحديد نقاط متابعة مناسبة من المعلومات التي أقدّمها.",helper:"راجع فقط المعلومات التي أشاركها هنا"},{id:"message",title:"ساعدني في صياغة رسالة داعمة للمريض أو للعائلة.",helper:"أنشئ صياغة واضحة لأراجعها"}]},
  fr:{greeting:"Bienvenue, {name}",dashboardSub:"Examinez les progrès thérapeutiques, préparez les prochaines séances et faites avancer le parcours de chaque patient.",heroTitle:"Chaque séance est une nouvelle étape vers un progrès concret.",heroBody:"Suivez les activités, les progrès et les rendez-vous afin de préparer un suivi attentif.",patientsEyebrow:"PROGRÈS THÉRAPEUTIQUES",patientsTitle:"Les progrès grandissent grâce à un soutien régulier.",patientsBody:"Suivez les activités, les séances et les progrès de chaque patient tout au long de son parcours thérapeutique.",patientsCta:"Voir tous les patients",appointmentsEyebrow:"SÉANCES THÉRAPEUTIQUES",appointmentsTitle:"Chaque séance ouvre la voie à des progrès significatifs.",appointmentsBody:"Préparez les prochaines séances et restez attentif au parcours de chaque patient.",aiLabel:"Assistant thérapeutique",aiDescription:"Une aide pour organiser les informations thérapeutiques, préparer les séances et planifier un suivi attentif.",aiHelp:"Je peux organiser les informations fournies, préparer des questions de séance, identifier des points de suivi et rédiger un message de soutien.",aiPlaceholder:"Demandez de l’aide pour organiser des informations ou préparer une séance...",aiSuggestions:[{id:"progress",title:"Aidez-moi à organiser les informations sur les progrès de ce patient.",helper:"Structurer uniquement les éléments que je fournis"},{id:"session",title:"Aidez-moi à préparer des questions pour la prochaine séance.",helper:"Organiser les questions et les points à aborder"},{id:"followup",title:"Aidez-moi à identifier des points de suivi utiles.",helper:"Examiner uniquement les informations partagées ici"},{id:"message",title:"Aidez-moi à rédiger un message de soutien au patient ou à sa famille.",helper:"Créer un texte clair que je pourrai relire"}]},
  es:{greeting:"Bienvenido, {name}",dashboardSub:"Revisa el progreso terapéutico, prepara las próximas sesiones y mantén en marcha el plan de cada paciente.",heroTitle:"Cada sesión es un nuevo paso hacia un progreso significativo.",heroBody:"Revisa actividades, progreso y citas para preparar un seguimiento atento.",patientsEyebrow:"PROGRESO TERAPÉUTICO",patientsTitle:"El progreso crece con apoyo constante.",patientsBody:"Sigue las actividades, sesiones y avances de cada paciente durante su proceso terapéutico.",patientsCta:"Ver todos los pacientes",appointmentsEyebrow:"SESIONES TERAPÉUTICAS",appointmentsTitle:"Cada sesión abre espacio para un progreso significativo.",appointmentsBody:"Prepara las próximas sesiones y mantente conectado con el proceso de cada paciente.",aiLabel:"Asistente terapéutico",aiDescription:"Apoyo para organizar información terapéutica, preparar sesiones y planificar un seguimiento atento.",aiHelp:"Puedo organizar la información que compartas, preparar preguntas, identificar puntos de seguimiento y redactar comunicaciones de apoyo.",aiPlaceholder:"Pide ayuda para organizar información o preparar una sesión...",aiSuggestions:[{id:"progress",title:"Ayúdame a organizar la información sobre el progreso de este paciente.",helper:"Estructura solo los detalles que proporcione"},{id:"session",title:"Ayúdame a preparar preguntas para la próxima sesión terapéutica.",helper:"Organiza preguntas y puntos de conversación"},{id:"followup",title:"Ayúdame a identificar puntos útiles de seguimiento.",helper:"Revisa solo la información compartida aquí"},{id:"message",title:"Ayúdame a redactar un mensaje de apoyo para el paciente o la familia.",helper:"Crea un texto claro para que pueda revisarlo"}]},
  de:{greeting:"Willkommen, {name}",dashboardSub:"Prüfen Sie Therapiefortschritte, bereiten Sie kommende Sitzungen vor und begleiten Sie den Plan jedes Patienten.",heroTitle:"Jede Sitzung ist ein weiterer Schritt zu spürbarem Fortschritt.",heroBody:"Verfolgen Sie Aktivitäten, Fortschritte und Termine für eine aufmerksame Nachverfolgung.",patientsEyebrow:"THERAPIEFORTSCHRITT",patientsTitle:"Fortschritt wächst durch beständige Unterstützung.",patientsBody:"Begleiten Sie Aktivitäten, Sitzungen und Fortschritte jedes Patienten auf dem Therapieweg.",patientsCta:"Alle Patienten ansehen",appointmentsEyebrow:"THERAPIESITZUNGEN",appointmentsTitle:"Jede Sitzung schafft Raum für bedeutsamen Fortschritt.",appointmentsBody:"Bereiten Sie kommende Therapiesitzungen vor und begleiten Sie den Weg jedes Patienten.",aiLabel:"Therapieassistent",aiDescription:"Unterstützung beim Strukturieren von Therapieinformationen, Vorbereiten von Sitzungen und Planen einer aufmerksamen Nachverfolgung.",aiHelp:"Ich kann bereitgestellte Informationen strukturieren, Sitzungsfragen vorbereiten, Nachverfolgungspunkte erkennen und unterstützende Nachrichten entwerfen.",aiPlaceholder:"Bitten Sie um Hilfe beim Strukturieren von Informationen oder Vorbereiten einer Sitzung...",aiSuggestions:[{id:"progress",title:"Helfen Sie mir, Informationen zum Fortschritt dieses Patienten zu ordnen.",helper:"Nur die von mir bereitgestellten Angaben strukturieren"},{id:"session",title:"Helfen Sie mir, Fragen für die nächste Therapiesitzung vorzubereiten.",helper:"Fragen und Gesprächspunkte strukturieren"},{id:"followup",title:"Helfen Sie mir, sinnvolle Nachverfolgungspunkte zu erkennen.",helper:"Nur die hier geteilten Informationen prüfen"},{id:"message",title:"Helfen Sie mir, eine unterstützende Nachricht zu entwerfen.",helper:"Klare Formulierung zur Prüfung erstellen"}]},
};

export const providerRole = (roles: string[]): ProviderRole => roles.includes("doctor") ? "doctor" : "therapist";
export const therapistExperience = (lang: Lang) => therapist[lang];
