import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api/client";
import { isRecent, loadCareData, reviewStatus, type CareData } from "../lib/careData";
import { useI18n } from "../i18n/useI18n";
import { useClinicianNotificationPreferences } from "../clinicianNotificationPreferences";

type Kind="message"|"appointment"|"review"|"activity";
type Item={id:string;kind:Kind;title:string;patient:string;helper:string;at:string;to:string;realUnread?:boolean};
type ReadState={read:string[]};
const copy={
 ar:{title:"الإشعارات",all:"الكل",unread:"غير المقروءة",mark:"تحديد الكل كمقروء",empty:"لا توجد إشعارات",message:"رسالة عائلية غير مقروءة",messageHelp:"توجد رسالة جديدة من العائلة.",appointment:"موعد قادم",appointmentHelp:"موعد مجدول للمريض.",review:"عنصر في قائمة المراجعة",reviewHelp:"توجد متابعة مسجلة في سير المراجعة.",activity:"جلسة مريض مسجلة",activityHelp:"تم تسجيل نشاط جديد للمريض.",now:"الآن",future:"خلال",day:"ي",hour:"س",minute:"د"},
 en:{title:"Notifications",all:"All",unread:"Unread",mark:"Mark all as read",empty:"No notifications",message:"Unread Family message",messageHelp:"A new Family message is available.",appointment:"Upcoming appointment",appointmentHelp:"A patient appointment is scheduled.",review:"Review Queue item",reviewHelp:"A recorded follow-up is available in the review workflow.",activity:"Patient session recorded",activityHelp:"New patient activity has been recorded.",now:"Now",future:"In",day:"d",hour:"h",minute:"m"},
 fr:{title:"Notifications",all:"Toutes",unread:"Non lues",mark:"Tout marquer comme lu",empty:"Aucune notification",message:"Message familial non lu",messageHelp:"Un nouveau message familial est disponible.",appointment:"Rendez-vous à venir",appointmentHelp:"Un rendez-vous patient est planifié.",review:"Élément à réviser",reviewHelp:"Un suivi enregistré est disponible.",activity:"Session patient enregistrée",activityHelp:"Une nouvelle activité patient a été enregistrée.",now:"Maintenant",future:"Dans",day:"j",hour:"h",minute:"min"},
 es:{title:"Notificaciones",all:"Todas",unread:"No leídas",mark:"Marcar todo como leído",empty:"No hay notificaciones",message:"Mensaje familiar no leído",messageHelp:"Hay un nuevo mensaje familiar.",appointment:"Próxima cita",appointmentHelp:"Hay una cita programada.",review:"Elemento para revisión",reviewHelp:"Hay un seguimiento registrado disponible.",activity:"Sesión de paciente registrada",activityHelp:"Se registró nueva actividad del paciente.",now:"Ahora",future:"En",day:"d",hour:"h",minute:"min"},
 de:{title:"Benachrichtigungen",all:"Alle",unread:"Ungelesen",mark:"Alle als gelesen markieren",empty:"Keine Benachrichtigungen",message:"Ungelesene Familiennachricht",messageHelp:"Eine neue Familiennachricht ist verfügbar.",appointment:"Anstehender Termin",appointmentHelp:"Ein Patiententermin ist geplant.",review:"Eintrag in der Prüfliste",reviewHelp:"Eine dokumentierte Nachverfolgung ist verfügbar.",activity:"Patientensitzung erfasst",activityHelp:"Neue Patientenaktivität wurde erfasst.",now:"Jetzt",future:"In",day:"T",hour:"Std.",minute:"Min."},
};

const bell=<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>;
const icon:Record<Kind,string>={message:"✉",appointment:"▣",review:"✓",activity:"◷"};
const dateForAppointment=(date:string,time?:string|null)=>`${date}T${time||"23:59"}`;

export function ClinicianNotificationCenter({providerUserId}:{providerUserId:string}){
 const {lang}=useI18n(),c=copy[lang],navigate=useNavigate();
 const {preferences}=useClinicianNotificationPreferences(providerUserId);
 const [open,setOpen]=useState(false),[tab,setTab]=useState<"all"|"unread">("all"),[data,setData]=useState<CareData|null>(null),[read,setRead]=useState<Set<string>>(new Set());
 const storageKey=`nb_clinician_notification_state:${providerUserId}`;
 const load=async()=>{try{setData(await loadCareData())}catch{/* The topbar remains usable if one source is unavailable. */}};
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)||"{}") as ReadState;setRead(new Set(Array.isArray(saved.read)?saved.read:[]))}catch{setRead(new Set())}},[storageKey]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(timer)},[]);
 const items=useMemo<Item[]>(()=>{if(!data)return[];const out:Item[]=[];for(const patient of data.patients){if(preferences.messages)for(const message of patient.messages){if((message.unread_reply_count??0)>0)out.push({id:`message:${message.id}`,kind:"message",title:c.message,patient:patient.name,helper:c.messageHelp,at:message.latest_reply_at??message.created_at,to:"/messages",realUnread:true})}if(preferences.appointments)for(const appointment of patient.appointments){const at=dateForAppointment(appointment.preferred_date,appointment.preferred_time);if(+new Date(at)>=Date.now()&&!['cancelled','completed'].includes(appointment.status))out.push({id:`appointment:${appointment.id}`,kind:"appointment",title:c.appointment,patient:patient.name,helper:c.appointmentHelp,at,to:"/appointments"})}if(preferences.review){const status=reviewStatus(patient);if(status.status!=="idle")out.push({id:`review:${patient.profile.id}:${status.status}`,kind:"review",title:c.review,patient:patient.name,helper:c.reviewHelp,at:patient.lastActivityAt??patient.profile.updated_at,to:"/review-queue"})}if(preferences.activity)for(const result of patient.results){if(result.completed&&isRecent(result.created_at))out.push({id:`activity:${result.id}`,kind:"activity",title:c.activity,patient:patient.name,helper:`${data.gameName(result.game_definition_id)} · ${c.activityHelp}`,at:result.created_at,to:`/patients/${patient.profile.id}`})}}return out.sort((a,b)=>+new Date(b.at)-+new Date(a.at))},[data,c,preferences]);
 const isUnread=(item:Item)=>item.realUnread||!read.has(item.id),unreadCount=items.filter(isUnread).length,shown=tab==="unread"?items.filter(isUnread):items;
 const persist=(next:Set<string>)=>{setRead(next);localStorage.setItem(storageKey,JSON.stringify({read:[...next]} satisfies ReadState))};
 const openItem=(item:Item)=>{if(!item.realUnread){const next=new Set(read);next.add(item.id);persist(next)}setOpen(false);navigate(item.to)};
 const markAll=async()=>{const next=new Set(read);items.filter(item=>!item.realUnread).forEach(item=>next.add(item.id));persist(next);const messageIds=data?.patients.flatMap(patient=>patient.messages.filter(message=>(message.unread_reply_count??0)>0).map(message=>message.id))??[];await Promise.all(messageIds.map(id=>api(`/provider-messages/${id}/read`,{method:"PATCH"}).catch(()=>undefined)));void load()};
 const relative=(iso:string)=>{const delta=Math.floor((Date.now()-new Date(iso).getTime())/1000),seconds=Math.abs(delta);let value=seconds<60?c.now:seconds<3600?`${Math.floor(seconds/60)}${c.minute}`:seconds<86400?`${Math.floor(seconds/3600)}${c.hour}`:`${Math.floor(seconds/86400)}${c.day}`;if(delta<0&&value!==c.now)value=`${c.future} ${value}`;return value};
 return <div className="clinician-notifications"><button className="provider-header-icon clinician-notifications__bell" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-label={c.title}>{bell}{unreadCount>0&&<b>{unreadCount>99?"99+":unreadCount}</b>}</button>{open&&<section className="clinician-notifications__panel"><header><h2>{c.title}</h2>{unreadCount>0&&<button type="button" onClick={()=>void markAll()}>{c.mark}</button>}</header><div className="clinician-notifications__tabs"><button className={tab==="all"?"is-active":""} onClick={()=>setTab("all")}>{c.all}</button><button className={tab==="unread"?"is-active":""} onClick={()=>setTab("unread")}>{c.unread}{unreadCount>0&&<span>{unreadCount}</span>}</button></div><div className="clinician-notifications__list">{shown.length===0?<p>{c.empty}</p>:shown.map(item=><button type="button" key={item.id} className={isUnread(item)?"is-unread":""} onClick={()=>openItem(item)}><i className={`is-${item.kind}`} aria-hidden="true">{icon[item.kind]}</i><span><strong>{item.title}</strong><b>{item.patient}</b><small>{item.helper}</small></span><time dateTime={item.at}>{relative(item.at)}</time></button>)}</div></section>}</div>;
}
